# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy 

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: demo4
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./demo4
          push: true
          tags: hiba1999/react:latest
      -
          name: Pull Docker Image
          run: docker pull hiba1999/react:latest
         
     # -  
      #{  name: Déploiement sur le serveur distant
       # uses: thematchless/bump-image-version-action@v2
        #with:
        # remote_docker_host: useradm@192.168.56.20
        # service_name: my-react-app-with-nginx
        # ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        # ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        # deploy_path: /demo4/demo4
        # args: up -d
        # pull_images_first: true
        # remote_docker_port: 22
        
