name: Build and Deploy Docker Image

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: ./demo4
          push: true
          tags: hiba1999/react:latest

      - name: Pull Docker Image
        run: docker pull hiba1999/react:latest

      - name: Deploy to Remote Server
        run: |
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} useradm@192.168.56.20 "docker stop my-react-app-with-nginx && docker rm my-react-app-with-nginx"
          ssh -i ${{ secrets.SSH_PRIVATE_KEY }} useradm@192.168.56.20 "docker run -d -p 8080:80 --name my-react-app-with-nginx hiba1999/react:latest"
