name: Deploy React App

on:
  push:
    branches:
      - master # Change this to your main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18 # Use the Node.js version you need

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

  #  - name: Deploy to Hosting
      # Add the deployment steps here depending on your hosting service.
      # Example for GitHub Pages:
#      run: |
 #       git config --global user.name "GitHub Actions"
  #      git config --global user.email "actions@github.com"
   #     npm install -g gh-pages
    #    gh-pages -d build # Deploy to GitHub Pages

# Add additional steps or jobs for deploying to other hosting services if needed.
